# Generated by Django 6.0.5 on 2026-06-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, help_text='Short summary shown on the landing page', max_length=500)),
                ('icon', models.CharField(default='bi bi-heart-pulse-fill', help_text='Bootstrap icon class', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health Article',
                'verbose_name_plural': 'Health Articles',
                'db_table': 'health_articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
