# Generated by Django 6.0.5 on 2026-06-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('address', 'Address'), ('hours', 'Working Hours')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(default='bi bi-telephone-fill', max_length=50)),
                ('value', models.CharField(max_length=300)),
                ('value_2', models.CharField(blank=True, help_text='Secondary value (e.g. second phone number)', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
                'db_table': 'contact_infos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(default='bi bi-hospital', help_text='Bootstrap icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'landing_departments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Quality Healthcare for You and Your Family', max_length=300)),
                ('subheading', models.CharField(default='Providing compassionate, affordable and professional healthcare services for all ages.', max_length=500)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('book_appointment_btn_text', models.CharField(default='Book Appointment', max_length=100)),
                ('contact_us_btn_text', models.CharField(default='Contact Us', max_length=100)),
                ('staff_login_btn_text', models.CharField(default='Staff Login', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'db_table': 'hero_sections',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(default='bi bi-hospital', help_text='Bootstrap icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'db_table': 'service_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Hope Medi - Clinic', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Quality Healthcare for You and Your Family', max_length=300)),
                ('meta_description', models.TextField(blank=True, default='Providing compassionate, affordable and professional healthcare services for all ages.')),
                ('meta_keywords', models.CharField(blank=True, default='healthcare, clinic, hospital, OPD, antenatal care, family planning, immunization, laboratory, pharmacy', max_length=500)),
                ('phone', models.CharField(blank=True, default='+265 999 401 674', max_length=50)),
                ('phone_2', models.CharField(blank=True, default='+254 700 100 300', max_length=50)),
                ('email', models.EmailField(blank=True, default='info@hopeclinic.co.ke', max_length=254)),
                ('email_2', models.EmailField(blank=True, default='admin@hopeclinic.co.ke', max_length=254)),
                ('address', models.CharField(blank=True, default='Chinamwali, Zomba - Malawi', max_length=300)),
                ('address_detail', models.CharField(blank=True, default='Next to City Hospital', max_length=300)),
                ('working_hours', models.CharField(blank=True, default='Mon - Sat: 7:00 AM - 8:00 PM', max_length=200)),
                ('sunday_hours', models.CharField(blank=True, default='Sunday: Closed (Emergencies Only)', max_length=200)),
                ('emergency_phone', models.CharField(blank=True, default='+254 700 100 300', max_length=50)),
                ('facebook_url', models.URLField(blank=True, default='#')),
                ('twitter_url', models.URLField(blank=True, default='#')),
                ('instagram_url', models.URLField(blank=True, default='#')),
                ('youtube_url', models.URLField(blank=True, default='#')),
                ('map_embed_url', models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15955.000000000!2d36.8219!3d-1.2921!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMcKwMTcnMzEuNyJTIDM2wrA0OScxOC44IkU!5e0!3m2!1sen!2ske!4v1')),
                ('footer_about', models.TextField(blank=True, default='Providing compassionate, affordable and professional healthcare services for all ages. Your health is our priority.')),
                ('copyright_text', models.CharField(blank=True, default='All rights reserved. Powered by HMS.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.PositiveIntegerField(default=0, help_text='Target number for the animated counter')),
                ('icon', models.CharField(default='bi bi-people-fill', help_text='Bootstrap icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'db_table': 'landing_statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('designation', models.CharField(blank=True, default='Patient', max_length=200)),
                ('avatar_color', models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('info', 'Teal'), ('warning', 'Orange'), ('danger', 'Red'), ('secondary', 'Gray')], default='primary', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi bi-heart-fill', help_text='Bootstrap icon class', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Item',
                'db_table': 'why_choose_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.servicecategory')),
            ],
            options={
                'verbose_name': 'Service Item',
                'db_table': 'service_items',
                'ordering': ['order'],
            },
        ),
    ]
