# Generated by Django 6.0.5 on 2026-06-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_contactinfo_department_herosection_servicecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_heading',
            field=models.CharField(blank=True, default='Why Choose {site_name}', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_subtitle',
            field=models.TextField(blank=True, default='We are committed to providing the highest standard of medical care with compassion and professionalism.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='appointment_btn_text',
            field=models.CharField(blank=True, default='Submit Appointment Request', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='appointment_bullet_1',
            field=models.CharField(blank=True, default='Same-day appointments available', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='appointment_bullet_2',
            field=models.CharField(blank=True, default='Minimal waiting time', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='appointment_bullet_3',
            field=models.CharField(blank=True, default='Professional medical team', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='appointment_bullet_4',
            field=models.CharField(blank=True, default='Affordable consultation fees', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='appointment_form_title',
            field=models.CharField(blank=True, default='Request Appointment', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='appointment_heading',
            field=models.CharField(blank=True, default='Book an Appointment', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='appointment_subtitle',
            field=models.CharField(blank=True, default="Schedule your visit today. We'll confirm your appointment promptly.", max_length=300),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_heading',
            field=models.CharField(blank=True, default='Contact Us', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_subtitle',
            field=models.TextField(blank=True, default="We'd love to hear from you. Reach out to us through any of the channels below."),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='departments_heading',
            field=models.CharField(blank=True, default='Our Departments', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='departments_subtitle',
            field=models.TextField(blank=True, default='Specialized departments working together for comprehensive healthcare delivery.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='doctors_heading',
            field=models.CharField(blank=True, default='Our Medical Team', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='doctors_subtitle',
            field=models.TextField(blank=True, default='Meet our dedicated team of healthcare professionals committed to your wellbeing.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='health_heading',
            field=models.CharField(blank=True, default='Health Education', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='health_search_placeholder',
            field=models.CharField(blank=True, default='Search health tips...', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='health_subtitle',
            field=models.TextField(blank=True, default='Empowering our community with knowledge for better health outcomes.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='services_heading',
            field=models.CharField(blank=True, default='Our Services', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='services_subtitle',
            field=models.TextField(blank=True, default='Comprehensive healthcare services tailored to meet the needs of our community.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='testimonials_heading',
            field=models.CharField(blank=True, default='What Our Patients Say', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='testimonials_subtitle',
            field=models.TextField(blank=True, default='Hear from our patients about their experience at {site_name}.'),
        ),
    ]
