# Generated by Django 6.0.5 on 2026-06-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sitesetting_about_heading_sitesetting_about_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='headline',
            field=models.CharField(default='Quality care for all', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tagline',
            field=models.CharField(blank=True, default='Quality care for all', max_length=300),
        ),
    ]
