# Generated by Django 6.0.5 on 2026-06-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_herosection_headline_alter_sitesetting_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Short tagline shown on the landing page', max_length=300),
        ),
        migrations.AddField(
            model_name='department',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='List of job roles / professionals in this department'),
        ),
    ]
