# Generated by Django 6.0.5 on 2026-06-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_department_description_department_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(default='bi bi-people-fill', help_text='Bootstrap icon class', max_length=50)),
                ('description', models.CharField(blank=True, default='', help_text='Short tagline shown on the landing page', max_length=300)),
                ('head_title', models.CharField(default='Team Lead', help_text='e.g. "Lead Physician", "Head Nurse"', max_length=100)),
                ('roles', models.JSONField(blank=True, default=list, help_text='List of roles / professionals in the team')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medical Team',
                'verbose_name_plural': 'Medical Teams',
                'db_table': 'landing_medical_teams',
                'ordering': ['order'],
            },
        ),
    ]
