# Generated by Django 6.0.5 on 2026-06-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_medicalteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='client_handling_steps',
            field=models.JSONField(blank=True, default=list, help_text='Step-by-step flow of how a client is received and discharged'),
        ),
        migrations.AddField(
            model_name='department',
            name='opening_hours',
            field=models.CharField(blank=True, default='Mon - Fri: 07:30 - 17:00 | Sat: 08:00 - 12:00 | Sun & Holidays: Closed', help_text='Service hours shown to the public', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='referrals_from',
            field=models.JSONField(blank=True, default=list, help_text='Departments / entry points that typically refer patients INTO this one (entry points)'),
        ),
        migrations.AddField(
            model_name='department',
            name='referrals_to',
            field=models.JSONField(blank=True, default=list, help_text='Departments / specialists that patients are referred OUT TO from this one (exit points)'),
        ),
    ]
