# Generated by Django 6.0.5 on 2026-06-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_department_client_handling_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='treatments',
            field=models.JSONField(blank=True, default=list, help_text='List of treatments or support services typically given to patients in this department'),
        ),
    ]
