# Generated by Django 5.2.3 on 2026-06-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_department_treatments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='accent_color',
            field=models.CharField(default='#f59e0b', help_text='Accent / warning color', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='body_bg',
            field=models.CharField(default='#f8fafc', help_text='Page body background color', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='card_bg',
            field=models.CharField(default='#ffffff', help_text='Card background color', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='card_border',
            field=models.CharField(default='rgba(0,0,0,.04)', help_text='Card border color', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_color',
            field=models.CharField(default='#0d9488', help_text='Main brand color (e.g. #0d9488)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_dark',
            field=models.CharField(default='#0f766e', help_text='Darker primary variant', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_light',
            field=models.CharField(default='#14b8a6', help_text='Lighter primary variant', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sidebar_bg_end',
            field=models.CharField(default='#1e293b', help_text='Sidebar gradient end color', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sidebar_bg_start',
            field=models.CharField(default='#0f172a', help_text='Sidebar gradient start color', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='text_muted',
            field=models.CharField(default='#94a3b8', help_text='Muted text color', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='text_primary',
            field=models.CharField(default='#0f172a', help_text='Primary text color', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='topbar_bg',
            field=models.CharField(default='rgba(255,255,255,.85)', help_text='Topbar background', max_length=7),
        ),
    ]
