# Generated by Django 6.0.5 on 2026-06-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='medicine',
            field=models.ForeignKey(blank=True, help_text='Linked inventory item if the line was picked from the medicine list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='pharmacy.medicine'),
        ),
    ]
