from io import BytesIO
from django.http import HttpResponse
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def generate_report(request):
    report_type = request.data.get('type', 'patient')
    fmt = request.data.get('format', 'pdf')

    if fmt == 'pdf':
        buffer = BytesIO()
        p = canvas.Canvas(buffer, pagesize=A4)
        p.drawString(100, 800, f'{report_type.title()} Report')
        p.drawString(100, 780, 'Generated by HMS')
        p.showPage()
        p.save()
        buffer.seek(0)
        response = HttpResponse(buffer, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{report_type}_report.pdf"'
        return response
    elif fmt == 'csv':
        import csv
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="{report_type}_report.csv"'
        writer = csv.writer(response)
        writer.writerow(['Report', report_type])
        return response
    elif fmt == 'excel':
        import openpyxl
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = report_type
        ws.append(['Report', report_type])
        response = HttpResponse(
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        response['Content-Disposition'] = f'attachment; filename="{report_type}_report.xlsx"'
        wb.save(response)
        return response

    return HttpResponse('Invalid format')


@staff_member_required
def dashboard(request):
    from apps.patients.models import Patient
    from apps.appointments.models import Appointment
    from apps.billing.models import Invoice
    from apps.pharmacy.models import Prescription
    from apps.laboratory.models import LabRequest
    counts = {
        'patients': Patient.objects.count(),
        'appointments': Appointment.objects.count(),
        'invoices': Invoice.objects.count(),
        'prescriptions': Prescription.objects.count(),
        'lab_requests': LabRequest.objects.count(),
    }
    return render(request, 'reports/dashboard.html', {'counts': counts})
