# Generated by Django 6.0.5 on 2026-06-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_module_rolemodulepermission'),
        ('doctors', '0001_initial'),
        ('inpatient', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='StaffDepartment',
        ),
        migrations.AlterModelOptions(
            name='staffdepartment',
            options={'verbose_name': 'Staff Department', 'verbose_name_plural': 'Staff Departments'},
        ),
    ]
