# Generated by Django 6.0.5 on 2026-06-02 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options'),
        ('patients', '0002_alter_patient_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal (Staff)'), ('web', 'Public Website'), ('phone', 'Phone Call'), ('walk_in', 'Walk-in')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal (Staff)'), ('web', 'Public Website'), ('phone', 'Phone Call'), ('walk_in', 'Walk-in')], default='internal', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['source'], name='appointment_source_9d4619_idx'),
        ),
    ]
